# 01. 파이썬 기반의 머신러닝과 생태계 이해
</br></br>
[01] 머신러닝의 개념
*   데이터를 기반으로 패턴을 학습하고 결과를 예측하는 알고리즘
*   일정한 패턴을 찾기 어려운 코드에서 머신러닝은 솔루션을 제공함
    
    Ex) 언어 필터링 시, 문맥 파악

*   데이터 분석은 머신러닝 기반의 예측분석으로 변화하고 있음

</br></br>
[02] 머신러닝의 분류


1.   지도 학습
*   **분류**
*   **회귀**
*   추천 시스템
*   시각/음성 감지/인지
*   텍스트 분석,NLP


2.   비지도 학습
*   클러스터링
*   차원 축소
*   강화학습

</br></br>

[03] 데이터 전쟁

*   머신러닝의 단점
</br> -데이터에 의존적이다 : Garbage In, Garbage Out
</br> - 알고리즘과 모델 파라미터 중요 but, 데이터 준비하는 능력이 더 중요할 수 있다.

</br></br>

[04] 넘파이 (Numerical Python)
* 선형대수 기반의 프로그램을 위한 패키지

* 루프를 사용하지 않고 배열 연산이 가능함
</br> -> 대량 데이터 연산 가능

* API 측면에서 판다스의 편리성에는 미치지 못함

</br>

1. 넘파이 ndarry 개요
</br> ** shape : ndarray 크기








In [ ]:
import numpy as np

array1 = np.array([1,2,3])
print('array1 type:', type(array1))
print('array1 array 형태:', array1.shape)


array2 = np.array([[1,2,3],
                  [2,3,4]])
print('array2 type:', type(array2))
print('array2 array 형태:', array2.shape)


array3  = np.array([[1,2,3]])
print('array3 type:', type(array3))
print('array3 array 형태:', array3.shape)

array1 type: <class 'numpy.ndarray'>
array1 array 형태: (3,)
array2 type: <class 'numpy.ndarray'>
array2 array 형태: (2, 3)
array3 type: <class 'numpy.ndarray'>
array3 array 형태: (1, 3)


array1은 1차원의 array가 3개의 데이터를 가짐
</br>
array3은 2차원의 array로 1:row, 3:column을 가짐
</br>
array()는 리스트 객체가 주로 사용되며, []는 1차원, [[  ]]은 2차원 형태이다.

In [ ]:
print('array1:{:0}차원, array2:{:1}차원, array3:{:2}차원'.format(array1.ndim,array2.ndim,array3.ndim))

array1:1차원, array2:2차원, array3: 2차원


2. ndarry의 데이터 타입</br>
: 연산 내 같은 데이터 타입만 가능</br>
: 다른 유형의 데이터가 섞여 있을 경우, 크기가 큰 데이터 타입으로 형변환이 일괄 적용 된다</br>
 -> int < unicode
* 숫자형인 경우: </br>
 - int 형(8,16,32 bit) </br>
 - unsigned int 형(8,16,32 bit) </br>
 - float 형 (16,32,64,128 bit) </br>
 - complex 타입 : 더 큰 숫자값들을 위하여

In [ ]:
list1 = [1,2,3]
print(type(list1))
array1 = np.array(list1)
print(type(array1))
print(array1,array1.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int64


In [ ]:
list2 = [1,2,'test']
array2 = np.array(list2)
print(type(array2))
print(array2,array2.dtype)

list3 = [1,2,3.0]
array3 = np.array(list3)
print(array3,array3.dtype)

<class 'numpy.ndarray'>
['1' '2' 'test'] <U21
[1. 2. 3.] float64


- ndarray 타입 변경 : astype()

In [ ]:
array_int = np.array([1,2,3])
array_float = array_int.astype('float64')
print(array_float,array_float.dtype)

array_int1 = array_float.astype('int32')
print(array_int1,array_int1.dtype)

array_float1 = np.array([1.1,2.1,3.1])
array_int2 = array_float1.astype('int32')
print(array_int2, array_int2.dtype)

[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32


3. ndarray를 편리하게 생성하기 - arange, zeros, ones</br>
 : 연속값이나 0 또는 1로 초기화해 생성해야할 경우

</br>

- default 함수 인자 : stop</br>
 -> 0부터 stop 값인 10에서 -1을 더한 9까지의 연속 숫자 값으로 구성된 1차원 ndarray를 만들어 준다.


In [ ]:
sequence_array = np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int64 (10,)


- zeros() </br>
 : 모든 값을 0으로 채운 해당 shape 를 가진 ndarray를 반환합니다</br>
- ones()</br>
 : 모든 값을 1로 채운 해당 shape 를 가진 ndarray를 반환합니다.
- default : float64

In [ ]:
zero_array = np.zeros((3,2),dtype = 'int32')
print(zero_array)
print(zero_array.dtype,zero_array.shape)

one_array = np.ones((3,2))
print(one_array)
print(one_array.dtype, one_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


4. ndarray의 차원과 크기를 변경하는 reshape()</br>
 : 지정된 사이즈로 변경이 불가능하면 오류를 발생한다

In [ ]:
array1 = np.arange(10)
print('array1:\n',array1)

array2 = array1.reshape(2,5)
print('array2:\n', array2)

array3 = array1.reshape(5,2)
print('array3:\n',array3)

array1:
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [ ]:
array1.reshape(4,3)

ValueError: cannot reshape array of size 10 into shape (4,3)

- reshape()을 효율적으로 사용하기 </br>
  : 인자로 -1을 적용하는 경우 -> 원래 ndarray와 호환되는 새로운 shape로 변환해 줌


In [ ]:
array1 = np.arange(10)
print(array1)
array2 = array1.reshape(-1,5)
print('array2 shape:',array2.shape)
array3 = array1.reshape(5,-1)
print('array3 shape:', array3.shape)

- n개의 1차원 데이터를 고정된 k개의 칼럼을 가진 로우로 변환이 안되면, 에러 발생

In [ ]:
array1 = np.arange(10)
array4 = array1.reshape(-1,4)

- reshape(-1,1)</br>
  : 원본 ndarray가 어떤 형태라도 2차원의 (,1)으로 변환됨을 보장함

- stack , concat으로 결합할 때 ndarray의 형태 통일을 위해 유용하게 사용함

- tolist()</br>
  : 메서드를 이용해 리스트 자료형으로 변환 가능.</br>
  : 시각적 이해를 위해서 리스트 자료형 이용

In [ ]:
array1 = np.arange(8)
array3d = array1.reshape((2,2,2))
print('array3d:\n', array3d.tolist())

#3차원 ndarray를 2차원 ndarray로 변환
array5 = array3d.reshape(-1,1)
print('array5:\n', array5.tolist())
print('array5 shape:', array5.shape)

#1차원 ndarray를 2차원 ndarray로 변환
array6 = array1.reshape(-1,1)
print('array6:\n', array6.tolist())
print('array6 shape:', array6.shape)

5. 넘파이의 ndarray의 데이터 세트 선택하기 - 인덱싱(Indexing)</br>

- 특정한 데이터만 추출</br>
 : 원하는 위치의 인덱스 값을 지정하면 해당 위치의 데이터가 반환된다
- 슬라이싱(slicing) : 연속된 인덱스사으이 ndarray를 추출하는 방식</br>
 -> ':' 기호 사이에 시작 인덱스와 종료 인덱스를 표시하면 시작 인덱스에서 종료 인덱스-1 위치에 있는 데이터의 ndarray를 반환합니다.
- 팬시 인덱싱(Fancy Indexing) </br>
: 일정한 인덱싱 집합 형태로 지정해 해당 위치에 있는 데이터의 ndarray를 반환
- 불린 인덱싱(Boolean Inddexing)
</br> : 특정 조건에 해당하는지 여부인 Ture/False 값 인덱싱 집합을 기반으로 데이터 반환

- **단일 값 추출** : 한 개의 데이터만 추출하는 방법

In [ ]:
#1부터 9까지의 1차원 ndarray 생성
array1 = np.arange(start=1,stop=10)
print('array1:', array1)

#index는 0부터 시작하므로 array1[2]는 3번쨰 index 위치의 데이터 값을 의미
value = array1[2]
print('value:',value)
print(type(value))

-인덱스는 0부터 시작하므로 array1[2]의 값은 3번쨰 인덱스 위치의 데이터값을 의미한다</br>
-array1[2]의 타입은 더 이상 ndarray 타입이 아니고 ndarray 내의 데이터 값을 의미한다


- 인덱스 -1은 맨 뒤의 데이터값을 의미한다.</br> -2는 맨 뒤에서 두 번째에 있는 데이터값이다

In [ ]:
print('맨 뒤의 값:', array1[-1], '맨 뒤에서 두 번째 값:', array1[-2])

- 단일 인덱스를 이용한 ndarray 데이터값 수정

In [ ]:
array1[0] = 9
array1[8] = 0
print('array1:', array1)

- 다차원 ndarray에서 단일 값 추출하기</br>
 : 1차원과의 차이는 콤마(,)로 분리된 로우와 칼럼 위치의 인덱스를 통해 접근하는 것</br>
- axis 0 : row / axis 1 : column</br>
 EX) [row=0, col=1] = [axis0=0, axis1=1]</br>
 EX) 3차원의 경우 : [axis 0, axis 1, axis 2]

In [ ]:
array1d = np.arange(start=1,stop=10)
array2d = array1d.reshape(3,3)
print(array2d)

print('(row=0, col=0) index 가리키는 값:', array2d[0,0])
print('(row=0, col=1) index 가리키는 값:', array2d[0,1])
print('(row=1, col=0) index 가리키는 값:', array2d[1,0])
print('(row=2, col=2) index 가리키는 값:', array2d[2,2])

- **슬라이싱**</br>
 : ':' 기호를 이용해 연속한 데이터를 슬라이싱해서 추출할 수 있다.</br>
  : 시작인덱스 ~ (종료인덱스-1) 반환

In [ ]:
array1 = np.arange(start=1,stop=10)
array3 = array1[0:3]
print(array3)
print(type(array3))

1. ':' 기호 앞에 시작 인덱스를 생략하면, 맨 처음 인덱스인 0으로 간주
2. ':' 기호 뒤에 종료 인덱스를 생략하면, 맨 마지막 인덱스로 간주
3. ':' 기호 앞/뒤에 시작/종료 인덱스를 생략하면, 자동으로 맨 처음/맨 마지막 인덱스로 간주

In [ ]:
array1 = np.arange(start=1,stop=10)
array4 = array1[:3]
print(array4)

array5 = array1[3:]
print(array5)

array6 = array1[:]
print(array6)

- 2차원 슬라이싱</br>
 : 2차원 뒤의 인덱스를 없애면 1차원을 반환</br>
  EX) row 축의 첫 번째 row(axis0)를 반환함</br>
 : 3차원 뒤의 인덱스를 없애면 2차원을 반환

In [ ]:
array1d = np.arange(start=1,stop=10)
array2d = array1d.reshape(3,3)
print('array2d:\n', array2d)

print('array2d[0:2,0:2] \n', array2d[0:2,0:2])
print('array2d[1:3,0:3] \n', array2d[1:3,0:3])
print('array2d[1:3,:] \n', array2d[1:3,:])
print('array2d[:,:] \n', array2d[:,:])
print('array2d[:2,1:] \n', array2d[:2,1:])
print('array2d[:2,0] \n', array2d[:2,0])

In [ ]:
print(array2d[0])
print(array2d[1])
print('array2d[0] shape:',array2d[0].shape,'array2d[1] shape:', array2d[1].shape)

- **팬시 인덱싱(Fancy Indexing)**</br>
 : 인덱스 집합 지정시, 해당 위치의 인덱스에 해당하는 ndarray 반환함

In [ ]:
array1d = np.arange(start=1,stop=10)
array2d = array1d.reshape(3,3)

array3 = array2d[[0,1],2]
print('array2d[[0,1],2] =>', array3.tolist())

array4 = array2d[[0,1], 0:2]
print('array2d[[0,1], 0:2] =>', array4.tolist())

array5 = array2d[[0,1]]
print('array2d[[0,1]] =>', array5.tolist())

- **불린 인덱싱(Boolean Indexing)**</br>
  : 조건 필터링과 검색을 동시에 할 수 있다.</br>
  : [  ] 내에 조건문을 그대로 기재하기만 하면 된다

In [ ]:
array1d =np.arange(start=1,stop=10)
#[  ] 안에 array1d > 5 Boolean indexxing을 적용
array3 = array1d[array1d>5]
print('array1d>5 불린 인덱싱 결과 값:', array3)

-조건이 일어나는 법 알아보기

In [ ]:
array1d>5

In [ ]:
boolean_indexes = np.array([False, False, False, False, False,  True,  True,  True,  True])
array3 = array1d[boolean_indexes]
print('불린 인덱스로 필터링 결과:', array3)

In [ ]:
indexes = np.array([5,6,7,8])
array4 = array1d[indexes]
print('일반 인덱스로 필터링 결과:', array4)

-Step1 : array1d>5 와 같이 ndarray의 필터링 조건을 [  ] 안에 기재</br>
-Step2 : False 값은 무시하고 True 값에 해당하는 인덱스값만 저장(True 값 자체인 1을 저장하는 것이 아니라 True 값을 가진 인덱스를 저장한다는 것입니다)</br>
-Step3 : 저장된 인덱스 데이터 세트로 ndarray 조회

6. 행렬의 정렬 : sort()와 argsort()</br>
- 행렬 정렬</br>
  :np.sort( ) 넘파이에서 sort( )를 호출하는 방식</br>
  -> 원 행렬 유지한 채 원 행렬의 정렬된 행렬 반환</br>
  :ndarray.sort( ) 행렬자체에서 sort( )를 호출하는 방식</br>
  -> 원 행렬 자체를 정렬한 형태로 변환. None으로 반환


In [ ]:
org_array = np.array([3,1,9,5])
print('원본 행렬:', org_array)

#np.sort( )로 정렬
sort_array1 = np.sort(org_array)
print('np.sort( ) 호출 후 반환된 정렬 행렬:', sort_array1)
print('np.sort( ) 호출 후 원본 행렬:', org_array)

#ndarray.sort( )로 정렬
sort_array2 = org_array.sort()
print('org_array.sort( )호출 후 반환된 행렬:', sort_array2)
print('org_array.sort( )호출 후 원본 행렬:', org_array)

- 내림차순 정렬은 [::-1]을 적용한다.

In [ ]:
sort_array1_desc = np.sort(org_array)[::-1]
print('내림차순으로 정렬:', sort_array1_desc)

- 행렬이 2차원 이상일 경우에는 axis 축 값 설정을 통해 로우 방향, 칼럼 방향으로 정렬을 수행할 수 있다

In [ ]:
array2d = np.array([[8,12],
                    [7,1]])

sort_array2d_axis0 = np.sort(array2d,axis=0)
print('로우 방향으로 정렬:\n', sort_array2d_axis0)

sort_array2d_axis1 = np.sort(array2d,axis=1)
print('칼럼 방향으로 정렬:\n', sort_array2d_axis1)

- 정렬된 행렬의 인덱스를 반환하기</br>
 : np.argsort( ) 이용하여 원본 행렬이 정렬되었을 때 기존 원본 행렬의 원소에 대한 인덱스를 반환

In [ ]:
org_array = np.array([3,1,9,5])
sort_indicies = np.argsort(org_array)
print(type(sort_indicies))
print('행렬 정렬 시 원본 행렬의 인덱스:', sort_indicies)

<class 'numpy.ndarray'>
행렬 정렬 시 원본 행렬의 인덱스: [1 0 3 2]


- 내림차순 정렬은 역시 np.arrgsort( )[::-1] 적용한다

In [ ]:
org_array = np.array([3,1,9,5])
sort_indicies_desc = np.argsort(org_array)[::-1]
print('행렬 내림차순 정렬 시 원본 행렬의 인덱스:', sort_indicies_desc)

행렬 내림차순 정렬 시 원본 행렬의 인덱스: [2 3 0 1]


- argsort( ) </br>
 : 메타 데이터를 별도의 ndarray로 가져야 하는 넘파이에서 팬시 인덱스로 추출이 가능하게 해준다

In [ ]:
import numpy as np

name_array = np.array(['John', 'Mike', 'Sarah', 'Kate', 'Samuel'])
score_array = np.array([78, 95, 84, 98, 88])

sort_indices_asc = np.argsort(score_array)
print('성적 오름차순 정렬 시 score_array의 인덱스', sort_indices_asc)
print('성적 오름차순으로 name_array의 이름 출력', name_array[sort_indices_asc])

성적 오름차순 정렬 시 score_array의 인덱스 [0 2 4 1 3]
성적 오름차순으로 name_array의 이름 출력 ['John' 'Sarah' 'Samuel' 'Mike' 'Kate']


[05] 선형대수 연산 - 행렬 내적과 전치 행렬 구하기</br>
- 행렬 내적(행렬 곱)</br>
 : 두 행렬 A와 B는 np.dot( )을 이용해 계산이 가능하다.

In [ ]:
A = np.array([[1,2,3],
              [4,5,6]])
B = np.array([[7,8],
              [9,10],
              [11,12]])
dot_product = np.dot(A,B)
print('행렬 내적 결과:\n', dot_product)

행렬 내적 결과:
 [[ 58  64]
 [139 154]]


- 전치행렬</br>
 : 원 행렬에서 행과 열 위치를 교환한 원소로 구성한 행렬을 그 행렬의 전치행렬이라고 함

In [ ]:
A = np.array([[1,2],
              [3,4]])
transpose_mat = np.transpose(A)
print('A의 전치 행렬:\n', transpose_mat)

A의 전치 행렬:
 [[1 3]
 [2 4]]
