<a href="https://colab.research.google.com/github/shriver42/ESAA/blob/%ED%95%84%EC%82%AC-%EA%B3%BC%EC%A0%9C/0318_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

[01] 사이킷런 소개와 특징
 - 파이썬 머신러닝 라이브러리 중 가장 많이 사용되는 라이브러리 이다
 - Anaconda 설치하면 기본으로 사이킷런까지 설치가 완료된다

In [1]:
import sklearn
print(sklearn.__version__)

1.2.2


[02] 첫번째 머신러닝 만들어 보기 - 붓꽃 품종 예측하기
 - 분류(Classification)
  - 대표적인 지도학습(Supervised learning) 방법의 하나
  -명확한 정답으로 학습 시킨 후(학습 데이터 세트),</br> 미지의 정답을 예측하게 한다(테스트 데이터 세트)
 - 의사 결정 트리 기반 : DecisionTreeClassifier
 - 예측 프로세스</br>
    1. 데이터 세트 분리 : 학습/테스트 데이터로 분리</br>
    2. 모델 학습 : ML 알고리즘을 적용해 모델을 학습시킨다</br>
    3. 예측 수행 : 학습된 ML 모델을 통해 테스트 데이터의 분류 예측</br>
    4. 평가 : 테스트 데이터의 실제 결괏값을 비교해 ML 성능 평가

In [2]:
from sklearn.datasets  import load_iris                 #사이킷런 내에서 자체 제공하는 데이터 세트 생성
from sklearn.tree import DecisionTreeClassifier         #트리 기반 ML 알고리즘을 구현한 클래스의 모임
from sklearn.model_selection import train_test_split    #학습 데이터와 검증 데이터, 예측 데이터로 데이터 분리

In [3]:
import pandas as pd

#붓꽃  데이터 세트를 로딩합니다
iris = load_iris()

#iris.data는 Iris 데이터 세트에서 피처(feature)만으로 된 데이터를 numpy로 가지고 있습니다.
iris_data = iris.data

#iris.target은 붓꽃 데이터 세트에서 레이블(결정 값) 데이터를 numpy로 가지고 있습니다.
iris_label = iris.target
print('iris target 값:',iris_label)
print('iris target 값:',iris.target_names)

#붓꽃 데이터 세트를 자세히 보기 위해 DataFrame으로 변환합니다.
iris_df = pd.DataFrame(data=iris_data,columns=iris.feature_names)
iris_df['label']=iris.target
iris_df.head(3)

iris target 값: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
iris target 값: ['setosa' 'versicolor' 'virginica']


sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   

   label  
0      0  
1      0  
2      0

In [4]:
#학습용 데이터와 테스트용 데이터로 분리하기
#test_size = n : 전체 데이터 세트 중 테스트 데이터 세트의 비율
#random_state = n : 호출할 때마다 같은 학습/테스트 용 데이터 세트를 생성하기 위해 주어지는 난수 발생 값
#random state 난 seed와 같은 의미로, 숫자 자체에는 어떤 값을 지정해도 상관없다
X_train,X_test,y_train,y_test = train_test_split(iris_data,iris_label,test_size=0.2,random_state=11)

In [5]:
#DecisionTreeClassifier 객체 생성
dt_clf = DecisionTreeClassifier(random_state=11)

#학습 수행
dt_clf.fit(X_train,y_train)

DecisionTreeClassifier(random_state=11)

In [6]:
#학습이 완료된 DecisionTreeClassifier 객체에서 테스트 데이터 세트로 예측 수행
pred = dt_clf.predict(X_test)

In [7]:
#정확도 측정 : 예측 결과가 실제 레이블 값과 얼마나 정확하게 맞는 지 평가
#accuracy_socre(실제 레이블 데이터 세트,예측 레이블 데이터 세트)
from sklearn.metrics import accuracy_score
print('예측 정확도:{0:.4f}'.format(accuracy_score(y_test,pred)))

예측 정확도:0.9333


[03] 사이킷런의 기반 프레임워크 익히기
- Estimator 이해 및 fit() , predict() 매서드
- 지도 학습
 - 분류(Classification)와 회귀(regression)의 알고리즘을 구형함
 - Estimator 클래스 = Classifier + Regressor 클래스
- 비지도 학습
 - fit()은 지도 학습과 다르게 입력 데이터 형태에 맞춰 데이터를 변환하기 위한 사전 구조를 맞추는 작업임
 - 이후의 차원 변환, 클러스터링, 피처 추출 등의 실제 작업은 transform()으로 수행함
 - fit_transform() 도 있는데 이는 편리함은 있지만, 약간의 사용에 주의가 필요하다.

- 사이킷런의 주요 모듈
 - 예제 데이터 : sklearn.datasets
 - 피치 처리 : sklearn.preprocessing / sklearn.feature_selection / sklearn.feature_extraction
 - 피처 처리 & 차원 축소 : sklearn.decomposition
 - 데이터 분리, 검증 & 파라미터 축소 : sklearn.model_selection
 - 평가 : sklearn.metrics
 - ML 알고리즘 : sklearn.ensemble / sklearn.linear_model / sklearn.naive_bayes / sklearn.neighbors / sklearn.svm / sklearn.tree / sklearn.cluster
 - 유틸리티 : sklearn.pipeline

- 내장된 예제 데이터 세트
 - 사이킷런에는 예제로 활용할 수 있는 데이터 세트가 내장되어 있음</br>
  EX) datasets.load_boston() / datasets.load_breast_cancer() / datasets.load_diabetes() / datasets.load_digits() / datasets.load_iris()
 - fetch 계열 데이터는 최초 사용시 인터넷에 연결돼 있지 않으면 사용할 수 없다</br>
  EX) fetch_covtype() / fetch_20newsgroup() / fetch_olivetti_faces() / fetch_lfw_people() / fetch_lfw_pairs() / fetch_rcv1() / fetch_mldata()
 - 표본 데이터 생성</br>
  EX) datasets.make_classifications() / datasets.make_blobs()

In [8]:
from sklearn.datasets import load_iris

iris_data = load_iris()
print(type(iris_data))

#Bunch 클래스는 파이썬 딕셔너리 자료혀과 유사하다

<class 'sklearn.utils._bunch.Bunch'>


In [9]:
keys = iris_data.keys()
print('붓꽃 데이터 세트의 키들:',keys)

#데이터의 키는 피처들의 데이터 값을 가리킨다
#형태가 딕셔너리 이기에 추출하기 위해서는 ['data']를 이용하면 된다

붓꽃 데이터 세트의 키들: dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])


In [10]:
print('\n feature_names의 type:', type(iris_data.feature_names))
print(' feature_names의 shape:', len(iris_data.feature_names))
print(iris_data.feature_names)

print('\n target_names의 type:',type(iris_data.target_names))
print(' target_names의 shape:', len(iris_data.target_names))
print(iris_data.target_names)

print('\n target의 type:', type(iris_data.data))
print(' data의 shape:', iris_data.data.shape)
print(iris_data['data'])

print('\n target의 type:', type(iris_data.target))
print(' target의 shape:', iris_data.target.shape)
print(iris_data.target)


 feature_names의 type: <class 'list'>
 feature_names의 shape: 4
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']

 target_names의 type: <class 'numpy.ndarray'>
 target_names의 shape: 3
['setosa' 'versicolor' 'virginica']

 target의 type: <class 'numpy.ndarray'>
 data의 shape: (150, 4)
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 

[04] Model Selection 모듈 소개
- 학습/테스트 데이터 세트 분리 - train_test_split()
 - test_size : 전체 데이터에서 테스트 데이터를 얼마로 할 것인가 결정. 디폴트는 0.25
 - train_size : 전체 데이터에서 학습용 데이터 크기를 얼마로 할 것인가 결정. 보통 test_size를 결정함
 - shuffle : 데이터 분리 전 미리 섞을지를 결정함. 디폴트는 True
 - ranodm_state : 지정 하지 않으면, 수행할 때마다 다른 데이터를 생성함.
 - train_test_split() : 반환값은 튜플 형태.</br> 순차적으로 피처 데이터 세트, 테스트용 데이터 피처 세트, 학습용 데이터의 레이블 세트, 테스트용 데이터의 레이블 반환

In [11]:
#학습 세트 데이터로만 학습하고 문제 파악하기

from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

iris=load_iris()
dt_clf = DecisionTreeClassifier()
train_data = iris.data
train_label = iris.target
dt_clf.fit(train_data,train_label)

#학습 데이터 세트으로 예측 수행
pred = dt_clf.predict(train_data)
print('예측 정확도:', accuracy_score(train_label,pred))

예측 정확도: 1.0


In [12]:
#테스트 데이터 : 30%
#학습 데이터 : 70%
#random_state = 121 변경

from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split

dt_clf = DecisionTreeClassifier()
iris_data = load_iris()

X_train,X_test,y_train,y_test = train_test_split(iris_data.data,iris_data.target,test_size=0.3,random_state=121)


In [13]:
#모데르이 예측 정확도 측정하기
dt_clf.fit(X_train,y_train)
pred = dt_clf.predict(X_test)
print('예측 정확도:{0:.4f}'.format(accuracy_score(y_test,pred)))

예측 정확도:0.9556


- 교차 검증
 - 과적합(Overfitting) 문제 발생 가능</br> : 모델이 학습 데이터에만 과도하게 적용되어 실제 데이터에서는 성능이 과하게 떨어지는 경우
 - 과적합 방지를 위해 교차 검증을 통해 다양한 학습과 평가를
 - 데이터 세트 : 학습, 검증, 테스트 데이터로 나눌 수 있음
1. K 폴드 교차 검정
  - 가장 보편적인 방법
  -K개의 데이터 폴드 세트를 만드렁서 K번 만큼 각 폴드 세트에 학습과 검증 평가를 반복적으로 시행
  - KFold 와 stratifiedKFold 클래스 제공

In [14]:
#데이터 불러오기
#5개의 폴드 세트로 분리하는 KFold 객체 생성
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import KFold
import numpy as np

iris = load_iris()
features = iris.data
label = iris.target
dt_clf = DecisionTreeClassifier(random_state=156)

#5개의 폴드 세트로 분리하는 KFold 객체와 폴드 세트별 정확도를 담을 리스트 객체 생성ㅇ
kfold = KFold(n_splits = 5)
cv_accuracy = []
print('붓꽃 데이터 세트 크기:', features.shape[0])

붓꽃 데이터 세트 크기: 150


In [15]:
#학습과 검증을 반복해 예측 정확도를 측정
n_iter = 0

#KFold 객체의 split()를 호출하면 폴드 별 학습용, 검증용 테스트의 로우 인덱스를 array로 반환
for train_index, test_index in kfold.split(features):
  #kfold.split()으로 반환된 인덱스를 이용해 학습용,검증용 테스트 데이터 추출
  X_train, X_test = features[train_index], features[test_index]
  y_train, y_test = label[train_index], label[test_index]
  #학습 및 예측
  dt_clf.fit(X_train,y_train)
  pred=dt_clf.predict(X_test)
  n_iter += 1
  #반복 시마다 정확도 측정
  accuracy = np.round(accuracy_score(y_test,pred),4)
  train_size = X_train.shape[0]
  test_size = X_test.shape[0]
  print('\n{0} 교차 검증 정확도 :{1}, 학습 데이터 크기:{2}, 검증 데이터 크기:{3}'.format(n_iter,accuracy,train_size,test_size))
  print('#{0} 검증 세트 인덱스:{1}'.format(n_iter, test_index))
  cv_accuracy.append(accuracy)

#개별 iteration별 정확도를 합하여 평균 정확도 계산
print('\n## 평균 검증 정확도:', np.mean(cv_accuracy))


1 교차 검증 정확도 :1.0, 학습 데이터 크기:120, 검증 데이터 크기:30
#1 검증 세트 인덱스:[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

2 교차 검증 정확도 :0.9667, 학습 데이터 크기:120, 검증 데이터 크기:30
#2 검증 세트 인덱스:[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59]

3 교차 검증 정확도 :0.8667, 학습 데이터 크기:120, 검증 데이터 크기:30
#3 검증 세트 인덱스:[60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83
 84 85 86 87 88 89]

4 교차 검증 정확도 :0.9333, 학습 데이터 크기:120, 검증 데이터 크기:30
#4 검증 세트 인덱스:[ 90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119]

5 교차 검증 정확도 :0.7333, 학습 데이터 크기:120, 검증 데이터 크기:30
#5 검증 세트 인덱스:[120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137
 138 139 140 141 142 143 144 145 146 147 148 149]

## 평균 검증 정확도: 0.9


2. Stratified K 폴드
 - 불균형한 분포도를 가진 레이블(결정 클래스) 데이터 집합을 위한 방식
 - 원본 데이터의 레이블 분포 먼저 고려 후 학습과 검정 데이터 세트를 분배함
 - split() 매서드에 인자로 피처 데이터+레이블 데이터 세트도 필요함</br> cf) K 폴드의 경우 split() 안에 레이블 데이터 세트 입력할 필요 없다
 - 회귀(Regression)에서는 지원되지 않는다. </br>회귀는 연속형 숫자값이기에 분포를 정하는 의미가 없기 때문

In [16]:
#데이터의 레이블 분포도를 확인하기
import pandas as pd

iris = load_iris()
iris_df = pd.DataFrame(data=iris.data,columns=iris.feature_names)
iris_df['label'] = iris.target
iris_df['label'].value_counts()

0    50
1    50
2    50
Name: label, dtype: int64

In [17]:
#KFold 생성 후, 각 교차 검증 시마다 생성되는 학습/검증 레이블 데이터 값의 분포도 확인
kfold = KFold(n_splits=3)
n_iter=0
for train_index, test_index in kfold.split(iris_df):
  n_iter += 1
  label_train = iris_df['label'].iloc[train_index]
  label_test = iris_df['label'].iloc[test_index]
  print('## 교차 검증:{0}'.format(n_iter))
  print('학습 레이블 데이터 분포:\n', label_train.value_counts())
  print('검증 레이블 데이터 분포:\n', label_test.value_counts())
  iris_df['label'].value_counts()

## 교차 검증:1
학습 레이블 데이터 분포:
 1    50
2    50
Name: label, dtype: int64
검증 레이블 데이터 분포:
 0    50
Name: label, dtype: int64
## 교차 검증:2
학습 레이블 데이터 분포:
 0    50
2    50
Name: label, dtype: int64
검증 레이블 데이터 분포:
 1    50
Name: label, dtype: int64
## 교차 검증:3
학습 레이블 데이터 분포:
 0    50
1    50
Name: label, dtype: int64
검증 레이블 데이터 분포:
 2    50
Name: label, dtype: int64


In [18]:
#위의 예제를 StratifiedKFold 로 바꾸기
from sklearn.model_selection import StratifiedKFold

skf = StratifiedKFold(n_splits=3)
n_iter = 0

for train_index, test_index in skf.split(iris_df,iris_df['label']):
  n_iter += 1
  label_train = iris_df['label'].iloc[train_index]
  label_test = iris_df['label'].iloc[test_index]
  print('## 교차 검증{0}'.format(n_iter))
  print('학습 레이블 데이터 분포:\n', label_train.value_counts())
  print('검증 레이블 데이터 분포:\n', label_test.value_counts())

## 교차 검증1
학습 레이블 데이터 분포:
 2    34
0    33
1    33
Name: label, dtype: int64
검증 레이블 데이터 분포:
 0    17
1    17
2    16
Name: label, dtype: int64
## 교차 검증2
학습 레이블 데이터 분포:
 1    34
0    33
2    33
Name: label, dtype: int64
검증 레이블 데이터 분포:
 0    17
2    17
1    16
Name: label, dtype: int64
## 교차 검증3
학습 레이블 데이터 분포:
 0    34
1    33
2    33
Name: label, dtype: int64
검증 레이블 데이터 분포:
 1    17
2    17
0    16
Name: label, dtype: int64


In [19]:
#StratifiedKFold를 이용해서 데이터 분리하기

dt_clf = DecisionTreeClassifier(random_state = 156)

skfold = StratifiedKFold(n_splits=3)
n_iter = 0
cv_accuracy = []

#StratifiedKFold의 split() 호출시 반드시 레이블 뎅이터 세트도 추가 입력 필요
for train_index, test_index in skfold.split(features,label):
  #split() 으로 반환된 인덱스를 이용해 학습용, 검증용 테스트 데이터 추출
  X_train, X_test = features[train_index], features[test_index]
  y_train, y_test = label[train_index], label[test_index]
  #학습 및 예측
  dt_clf.fit(X_train,y_train)
  pred=dt_clf.predict(X_test)

  #반복 시마다 정확도 측정
  n_iter += 1
  accuracy = np.round(accuracy_score(y_test,pred),4)
  train_size = X_train.shape[0]
  teset_size = X_test.shape[0]
  print('\n#{0} 교차 검증 정확도 : {1}, 학습 데이터 크기: {2}, 검증 데이터 크기: {3}'.format(n_iter, accuracy, train_size, test_size))
  print('#{0} 검증 세트 인덱스:{1}'.format(n_iter, test_index))
  cv_accuracy.append(accuracy)

#교차 검증별 정확도 및 평균 정확도 계산
print('\n## 교차 검증별 정확도:', np.round(cv_accuracy, 4))
print('## 평균 검증 정확도:', np.mean(cv_accuracy))


#1 교차 검증 정확도 : 0.98, 학습 데이터 크기: 100, 검증 데이터 크기: 30
#1 검증 세트 인덱스:[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  50
  51  52  53  54  55  56  57  58  59  60  61  62  63  64  65  66 100 101
 102 103 104 105 106 107 108 109 110 111 112 113 114 115]

#2 교차 검증 정확도 : 0.94, 학습 데이터 크기: 100, 검증 데이터 크기: 30
#2 검증 세트 인덱스:[ 17  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  67
  68  69  70  71  72  73  74  75  76  77  78  79  80  81  82 116 117 118
 119 120 121 122 123 124 125 126 127 128 129 130 131 132]

#3 교차 검증 정확도 : 0.98, 학습 데이터 크기: 100, 검증 데이터 크기: 30
#3 검증 세트 인덱스:[ 34  35  36  37  38  39  40  41  42  43  44  45  46  47  48  49  83  84
  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99 133 134 135
 136 137 138 139 140 141 142 143 144 145 146 147 148 149]

## 교차 검증별 정확도: [0.98 0.94 0.98]
## 평균 검증 정확도: 0.9666666666666667


3. cross_val_score()
 - 교차 검증을 편리하게 수행할 수 있는 API 제공
 - 폴드 세트 성정, for 루프에서 반복 학습하고 인덱스 추출, 예측 수행 까지 다 수행함
 -classifier가 입력되면, Stratified K 폴드 방식로 레이블값의 분포에 따라 학습/데이터 세트 분리</br>
 회귀이면 K 폴드 방식으로 분할함
 - cross_val_score(estimator,X,y=None,scoring=None,cv=None) 가 주요 파라미터
 - cross_validate()은 여러 개의 평가 지표를 반환할 수 있음

In [20]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import cross_val_score, cross_validate
from sklearn.datasets import load_iris

iris_data = load_iris()
dt_clf = DecisionTreeClassifier(random_state = 156)

data = iris_data.data
label = iris_data.target

#성능 지표는 정확도(accuracy), 교차 검증 세트는 3개
scores = cross_val_score(dt_clf,data,label,scoring='accuracy',cv=3)    #cv로 지정한 횟수만큼 scoring 파라미터로 지정된 평가 지표로 평가 결괏값을 배열로 반환함
print('교차 검증별 정확도:',np.round(scores,4))
print('평균 검증 정확도:',np.round(np.mean(scores),4))

교차 검증별 정확도: [0.98 0.94 0.98]
평균 검증 정확도: 0.9667


4. GridSearchCV : 교차 검증과 최적 하이퍼 파라미터 튜닝을 한 번에
 - 수행 시간이 상대적으로 오래 걸림
 - CV가 3회라면, 개별 파라미터 조합마다 3개의 폴딩 세트를 3회에 걸쳐 학습/평가해 성능 측정
 - 주요 파라미터:</br>
  estimator : classifier,regressor,pipeline
  param_grid : key+리스트 값을 갖는 딕셔너리
  scoring : 예측 성능을 측정할 평가 방법 지정
  cv : 교차 검증을 위해 분할되는 학습/테스트 세트와 개수 지정ㅇ
  refit : 디폴트는 True, 가장 최적의 하이퍼 파라미터 찾은 후</br> 입력된 estimator 객체를 해당 하이퍼 파라미터로 재학습 시킴

In [21]:
grid_parameters = {'max_depth' : [1,2,3],
                   'min_samples_split':[2,3]
                   }
print(grid_parameters)

{'max_depth': [1, 2, 3], 'min_samples_split': [2, 3]}


In [22]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import GridSearchCV

#데이터를 로딩하고 학습 데이터와 테스트 데이터 분리
iris = load_iris()
X_train,X_test,y_train,y_test = train_test_split(iris_data.data,iris_data.target,test_size=0.2,random_state = 121)
dtree = DecisionTreeClassifier()

###파라미터를 딕셔너리 형태로 설정
parameters = {'max_depth':[1,2,3], 'min_samples_split':[2,3]}

In [23]:
import pandas as pd

#param_grid의 하이퍼 파라미터를 3개의 train,test set fold로 나누어 테스트 수행 설정
### refit=True가 default임. True 이면 가장 좋은 파라미터 설정으로 재학습시킴.
grid_dtree = GridSearchCV(dtree,param_grid = parameters,cv=3,refit=True)

#붓꽃 학습 데이터로 param_grid의 하이퍼 파라미터를 순차적으로 학습/평가
grid_dtree.fit(X_train,y_train)

#GridSearchCV 결과를 추출해 DataFrame으로 변환
scores_df = pd.DataFrame(grid_dtree.cv_results_)
scores_df[['params','mean_test_score','rank_test_score','split0_test_score','split1_test_score','split2_test_score']]

params  mean_test_score  rank_test_score  \
0  {'max_depth': 1, 'min_samples_split': 2}         0.700000                5   
1  {'max_depth': 1, 'min_samples_split': 3}         0.700000                5   
2  {'max_depth': 2, 'min_samples_split': 2}         0.958333                3   
3  {'max_depth': 2, 'min_samples_split': 3}         0.958333                3   
4  {'max_depth': 3, 'min_samples_split': 2}         0.975000                1   
5  {'max_depth': 3, 'min_samples_split': 3}         0.975000                1   

   split0_test_score  split1_test_score  split2_test_score  
0              0.700                0.7               0.70  
1              0.700                0.7               0.70  
2              0.925                1.0               0.95  
3              0.925                1.0               0.95  
4              0.975                1.0               0.95  
5              0.975                1.0               0.95

-  위의 자료 해석:
 - paramas 칼럼에는 수행할 때마다 적용된 개별 하이퍼 파라미터값을 나타낸다
 - rank_test_score는 하이퍼 파라미터별로 성능이 좋은 score 순위를 나타낸다.</br> 1이 가장 뛰어난 순위이며 이때의 파라미터가 최적의 하이퍼 파라미터 이다.
 - mean_test_score은 개별 하이퍼 파라미터 별로 CV 폴딩 테스트 세트에 대해 총 수행한 평가 평균값

In [24]:
print('GridSearchCV 최적 파라미터:', grid_dtree.best_params_)
print('GridSearchCV 최고 정확도 :{0:.4f}'.format(grid_dtree.best_score_))

GridSearchCV 최적 파라미터: {'max_depth': 3, 'min_samples_split': 2}
GridSearchCV 최고 정확도 :0.9750


In [25]:
#GridSearchCV의 refit으로 이미 학습된 estimator 반환
estimator = grid_dtree.best_estimator_

#GridSearchCV의 best_estimator_는 이미 최적 학습이 됐으므로 별도 학습이 필요 없음
pred = estimator.predict(X_test)
print('테스트 데이터 세트 정확도:{0:.4f}'.format(accuracy_score(y_test,pred)))

테스트 데이터 세트 정확도:0.9667
