<a href="https://colab.research.google.com/github/shriver42/ESAA/blob/%EC%97%B0%EC%8A%B5-%EB%AC%B8%EC%A0%9C/3_8_%EC%84%B8%EC%85%98_%EB%AC%B8%EC%A0%9C_Numpy_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [101]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [102]:
print(np.__version__)
np.show_config()

1.25.2
openblas64__info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
openblas64__lapack_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS

#### 3. Create a null vector of size 10 (★☆☆)

In [103]:
array1 = np.zeros(10)
print(array1)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [104]:
print(array1.size,array1.itemsize)
print("%d byte" % (array1.size*array1.itemsize))

10 8
80 byte


#### 5. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [105]:
array2 = np.zeros(10)
array2[4] = 1
print(array2)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 6. Create a vector with values ranging from 10 to 49 (★☆☆)

In [106]:
array3 = np.arange(start = 10, stop=50)
print(array3)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 7. Reverse a vector (first element becomes last) (★☆☆)

In [107]:
array3_desc = np.sort(array3)[::-1]
print(array3_desc)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 8. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [108]:
a = np.arange(0,9)
am = a.reshape(3,3)
print(am)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 9. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [109]:
non = np.array([1,2,0,0,4,0])
non1 = non[non!=0]
print(non1)

[1 2 4]


#### 10. Create a 3x3 identity matrix (★☆☆)
Hint : identity & eye, try to use 'help' to learn how to use two functions of numpy

In [110]:
identity_matrix = np.identity(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 11. Create a 3x3x3 array with random values (★☆☆)
Hint : numpy.random.random

In [111]:
array1 = np.random.random((3,3,3))
print(array1)

[[[0.27658059 0.72871896 0.33657755]
  [0.09845199 0.46712851 0.55358534]
  [0.10756972 0.33573838 0.56044895]]

 [[0.66676428 0.62181856 0.66475101]
  [0.85599916 0.87085781 0.14894471]
  [0.21359155 0.67960384 0.37365647]]

 [[0.90646824 0.91584215 0.40407878]
  [0.60699935 0.68309666 0.51126559]
  [0.24732538 0.10490074 0.81195428]]]


#### 12. Create a 10x10 array with random values and find the **min**imum and **max**imum values (★☆☆)

In [112]:
array1 = np.random.random((10,10))
Min = array1.min()
Max = array1.max()
print(Min,Max)
print(np.min(array1),np.max(array1))

0.0015445827766451536 0.9978535350708385
0.0015445827766451536 0.9978535350708385


#### 13. Create a random vector of size 30 and find the **mean** value (★☆☆)

In [113]:
array1 = np.random.random(30)
print(np.mean(array1))

0.4834366441788566


#### 14. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [114]:
array1 = np.ones((10,10))
array1[1:-1,1:-1] = 0
print(array1)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### 15. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [115]:
0 * np.nan
#NAN
np.nan == np.nan
#FALSE
np.inf > np.nan
#FALSE
np.nan - np.nan
#NAN
np.nan in set([np.nan])
#TRUE
0.3 == 3 * 0.1
#FALSE

False

#### 16. Create a 5x5 matrix with values 1,2,3,4 just below the **diag**onal (★☆☆)

In [116]:
array1 = np.zeros((5,5))
for i in range(5):
  for j in range(5):
    if(i-j)==1:
      array1[i][j] = i
print(array1)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


#### 17. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [117]:
array1 = np.zeros((8,8))

for i in range(8):
  for j in range(8):
    if (i+j)%2 == 0:
      array1[i][j] = 1
print(array1)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


#### 18. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)
Hint : use 'numpy.unravel_index(value, (x, y, z))

In [118]:
array1 = np.unravel_index(99,(6,7,8))
print(array1)

(1, 5, 3)


#### 19. Normalize a 5x5 random matrix (★☆☆)
Hint : $Z = \frac{X - \overline{X}}{S}$

In [119]:
array1 = np.random.random((5,5))
M = array1.mean()
S = array1.std()
Z = (array1-M) / S
print(Z)

[[-1.21134199 -0.73777769 -1.38164811  0.36254875  0.42388506]
 [-1.31390722 -0.83338279  0.29914619  1.44163581  0.37554228]
 [ 0.95754877  1.53592088 -0.78168368 -0.09557762  1.15164662]
 [-0.21693487 -1.77393456  0.99436261  0.52779025 -0.53459978]
 [ 0.36420528  1.17469935 -1.85474459  1.05414937  0.07245169]]


#### 20. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)
Hint : modify the code below
```python
numpy.dtype([(value, numpy.ubyte), … , (value, numpy.ubyte)])
```

In [120]:
color_dtype = np.dtype([("R", np.ubyte), ("G", np.ubyte), ("B", np.ubyte), ("A", np.ubyte)])
color_dtype

dtype([('R', 'u1'), ('G', 'u1'), ('B', 'u1'), ('A', 'u1')])

#### 21. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [121]:
matrix1 = np.random.random((5, 3))  # 5x3 행렬
matrix2 = np.random.random((3, 2))  # 3x2 행렬
product = np.dot(matrix1, matrix2)

print(product)

[[2.17324909 0.89288896]
 [0.44631733 0.15422317]
 [1.51439852 0.34765522]
 [0.9037666  0.54653404]
 [1.19326371 0.4985411 ]]


#### 22. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [122]:
array1 = np.arange(10,20)
array1[2:8] = array1[2:8]*(-1)
print(array1)

[ 10  11 -12 -13 -14 -15 -16 -17  18  19]


#### 23. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [123]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

10
10


#### 24. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [124]:
# Z<Z>Z 빼고는 다 가능한 표현들이다.
# << 는 left shift, >>는 right shift

#### 25. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [125]:
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

<ipython-input-125-cd809174da5d>:1: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0)
<ipython-input-125-cd809174da5d>:2: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)
<ipython-input-125-cd809174da5d>:3: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype(float)


array([-9.22337204e+18])

#### 26. How to find common values between two arrays? (★☆☆)
```python
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
```
Hint : use `numpy.random.randint(start, end, size)`

In [126]:
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(Z1,Z2)
print(np.intersect1d(Z1,Z2))

[5 5 8 2 4 2 3 4 1 7] [6 2 9 6 7 1 1 3 7 0]
[1 2 3 7]


#### 27. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [127]:
#False
#sqrt(-1)은 원래 불가능하지만, emath.sqrt(-1)로 j가 가능하게 해준다. 둘의 답은 다르다
np.sqrt(-1) == np.emath.sqrt(-1)

<ipython-input-127-8088fea4da73>:3: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


False

In [128]:
import numpy as np

#### 28. How to get all the dates corresponding to the month of July 2016? (★★☆)
Hint : modify the code below
```python
Z = np.arange('start', 'end', dtype='datetime64[D]')
```

In [129]:
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 29. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)
Hint : use `numpy.add`, `numpy.divide`,`numpy.negative`, `numpy.multiply` and parameter `out` of the funtions

In [130]:
def Com(A,B):
  A = np.multiply(np.add(A,B),np.divide(np.negative(A),2))
  return A

print(Com([3,5],[6,8]))

[-13.5 -32.5]


#### 30. Extract the integer part of a random array of positive numbers using 2 different methods (★★☆)
Hint : `%`, `//`

In [131]:
def ext(A):
  result = []
  for i in range((len(A))):
    if A[i] >0 :
      result.append(np.trunc(A[i]))
  return result

print(ext([9,5,-5,-7.8,5.6,1]))

[9.0, 5.0, 5.0, 1.0]


#### 31. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [132]:
ma = np.zeros((5,5))
for i in range(5):
  for j in range(5):
    ma[i,j] = j
print(ma)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 32. Create a random vector of size 10 and sort it (★★☆)

In [133]:
RV = np.random.random(10)
print(np.sort(RV))

[0.13660631 0.18266628 0.39763499 0.54586466 0.70643158 0.70996047
 0.8144123  0.8347121  0.89000001 0.89584753]


#### 33. Consider two random array A and B, check if they are equal (★★☆)
```python
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
```
Hint : Use `numpy.array_equal()`

In [134]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
print(np.array_equal(A,B))

False


#### 34. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)
Hint 1 : Note that cartesian coodinate **(x, y)** can be represented as  polar coordinates **(distance from origin to (x,y), angle from the x-axis)**

Hint 2 : Use `numpy.sqrt` and `numpy.arctan2`

In [135]:
Z = np.random.random((10,2))
print(Z)
result_R = []
result_T = []
for i in range(10):
  X = Z[i][0]
  Y = Z[i][1]
  result_R.append(np.sqrt(X**2+Y**2))
  result_T.append(np.arctan2(Y,X))
print(result_R,'\n',result_T)

[[0.81512844 0.1620977 ]
 [0.33023961 0.62008364]
 [0.54362642 0.79411399]
 [0.49559498 0.57427454]
 [0.71435239 0.16759142]
 [0.73625386 0.30501184]
 [0.1585233  0.15669837]
 [0.40535782 0.46757043]
 [0.65808482 0.4109991 ]
 [0.28653218 0.45232173]]
[0.8310896729058282, 0.7025396256555823, 0.9623651702914529, 0.7585549625620941, 0.7337480686121672, 0.7969328548639462, 0.2228991169654306, 0.618819095612022, 0.7758839457098459, 0.5354396676790713] 
 [0.19630064616615261, 1.081431384655196, 0.970501471024642, 0.8588072806396962, 0.23043863658764718, 0.3927518372745124, 0.7796088699125726, 0.856546732230229, 0.5582671569482255, 1.0061294925398376]


#### 35. Create random vector Z of size 10 and replace the maximum value by 0 (★★☆)
Hint : We can see the index of maximum value using `Z.argmax()`

In [136]:
Z = np.random.random(10)
print('Before replacing:\n', Z)
Z[Z.argmax()] = 0
print('After replacing:\n',Z)

Before replacing:
 [0.99138032 0.565751   0.71420858 0.19381145 0.991241   0.81396068
 0.75083225 0.44555934 0.3800401  0.38349793]
After replacing:
 [0.         0.565751   0.71420858 0.19381145 0.991241   0.81396068
 0.75083225 0.44555934 0.3800401  0.38349793]


#### 36. How to find the closest value (to a given scalar v) in a vector Z? (★★☆)
```python
Z = np.arange(100)
v = np.random.uniform(0,100)
```
Hint : Coumpute the distances between the each elements of Z and the scalar v. After that, we can see the index of minimum value using `argmin()`.  

In [137]:
Z = np.arange(100)
v = np.random.uniform(0,100)
dist = np.abs(Z-v)
index=dist.argmin()
print(v, Z[index])

46.66106590304763 47


#### 37. What is the equivalent of enumerate for numpy arrays? (★★☆)
Hint : Use `numpy.ndenumerate()`or `numpy.ndindex()`

Example of the output :
```python
Z = np.arange(9).reshape(3,3)
```
```python
# output
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
```

In [138]:
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
  print(index,value)

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 38. How to randomly place p elements in a 2D array? (★★☆)
Hint : modify the code below
```python
n = 'size of a 2D array'
p = 'the number of elements that you want to place'
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace = False),'value that you want to place')
print(Z)
```

In [139]:
Z = np.zeros((10,10))
np.put(Z,np.random.choice(range(10*10),14,replace=False),4)
print(Z)

[[0. 0. 4. 0. 0. 0. 4. 4. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 4. 4. 0. 4. 0. 0. 0.]
 [0. 0. 0. 4. 0. 0. 0. 0. 4. 0.]
 [4. 4. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 4. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 4. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 4. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 4. 0. 0.]]


#### 39. How to sort an array below by the nth column? (★★☆)
```python
Z = np.random.randint(0,10,(3,3))
```

In [140]:
# column 1
Z = np.random.randint(0,10,(3,3))
print(Z)
print(Z[Z[:,0].argsort()])

[[9 8 8]
 [5 7 6]
 [7 7 7]]
[[5 7 6]
 [7 7 7]
 [9 8 8]]


In [141]:
# column 2
Z = np.random.randint(0,10,(3,3))
print(Z)
print(Z[Z[:,1].argsort()])

[[8 4 7]
 [7 8 5]
 [7 6 7]]
[[8 4 7]
 [7 6 7]
 [7 8 5]]


In [142]:
# column 3
Z = np.random.randint(0,10,(3,3))
print(Z)
print(Z[Z[:,2].argsort()])

[[8 5 8]
 [1 5 3]
 [2 4 1]]
[[2 4 1]
 [1 5 3]
 [8 5 8]]
